name: swag-labs-testing
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: 1.1.0
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos